---
- name: Install and Configure Tomcat
  hosts: all
  become: yes

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Tomcat User
      user:
        name: tomcat
        shell: /bin/false

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
        dest: /tmp/tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set Permissions
      file:
        path: /opt/
        owner: tomcat
        group: tomcat
        mode: '0755'
        recurse: yes

    - name: Start Tomcat
      shell: nohup /opt/bin/startup.sh &
      async: 10
      poll: 0
